In [2]:
import os
os.chdir(r"C:\Users\darli\Documents\GitHub\ROM-Data-Analyser")
print(os.getcwd())

C:\Users\darli\Documents\GitHub\ROM-Data-Analyser

In [3]:
import pandas as pd

df = pd.read_csv("data/raw/injury_dataset.csv")
df.head()

,Player_ID,Age,Height_cm,Weight_kg,Position,Injury_Type,Injury_Severity,Rehabilitation_Program,Rehabilitation_Time_weeks,Injury_Recurrence,Date_of_Injury,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
0,1,24,195,108,Center,ACL Tear,Severe,Physiotherapy,7,0,2017-12-19,0.862860,78.327638,77.705191,37.926663,56.578469,64.259747
1,2,32,183,87,Forward,Ankle Sprain,Mild,Physiotherapy,8,0,2017-08-10,0.806708,32.751850,83.215950,98.938884,71.320646,45.484661
2,3,28,208,109,Center,Knee Injury,Moderate,Flexibility Exercises,3,0,2018-11-21,0.709122,85.958728,71.694712,88.722866,48.764455,99.136761
3,4,25,196,70,Forward,Shoulder Dislocation,Moderate,Strength Training,11,0,2017-07-18,0.966364,73.953027,63.010333,38.726388,73.690424,96.084154
4,5,24,178,80,Guard,Shoulder Dislocation,Moderate,Balance Training,3,1,2015-03-05,0.933032,35.723132,58.828864,94.458932,58.658816,32.759877

In [32]:
df.tail()

,Player_ID,Age,Height_cm,Weight_kg,Position,Injury_Type,Injury_Severity,Rehabilitation_Program,Rehabilitation_Time_weeks,Injury_Recurrence,Date_of_Injury,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
95,96,32,189,100,Center,Knee Injury,Mild,Physiotherapy,6,0,2021-11-25,0.560318,34.436248,59.689147,59.499719,86.459280,99.643548
96,97,31,201,72,Forward,Ankle Sprain,Moderate,Flexibility Exercises,11,1,2018-02-19,0.730389,99.297216,81.551096,92.487020,76.114836,42.172667
97,98,20,176,109,Guard,Ankle Sprain,Severe,Strength Training,11,0,2014-11-15,0.603167,52.564769,95.405691,87.221049,78.459360,57.736941
98,99,18,202,93,Center,Shoulder Dislocation,Mild,Balance Training,6,0,2018-03-27,0.682135,86.691211,94.789796,53.927215,89.443696,83.076693
99,100,22,209,101,Forward,Ankle Sprain,Severe,Balance Training,8,0,2021-10-30,0.751709,47.824846,61.558756,48.159640,47.476761,78.721443

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Player_ID                        100 non-null    int64
 1   Age                              100 non-null    int64
 2   Height_cm                        100 non-null    int64
 3   Weight_kg                        100 non-null    int64
 4   Position                         100 non-null    object
 5   Injury_Type                      100 non-null    object
 6   Injury_Severity                  100 non-null    object
 7   Rehabilitation_Program           100 non-null    object
 8   Rehabilitation_Time_weeks        100 non-null    int64
 9   Injury_Recurrence                100 non-null    int64
 10  Date_of_Injury                   100 non-null    object
 11  Rehabilitation_Efficiency_Score  100 non-null    float64
 12  knee_angle_deg                   100 non-null    float64
 13  jump_height_cm                   100 non-null    float64
 14  ankle_flexion_deg                100 non-null    float64
 15  speed_m_s                        100 non-null    float64
 16  reaction_time_ms                 100 non-null    float64
dtypes: float64(6), int64(6), object(5)
memory usage: 13.4+ KB

In [7]:
df.loc[:, ["Player_ID", "speed_m_s"]]

    Player_ID  speed_m_s
0           1  56.578469
1           2  71.320646
2           3  48.764455
3           4  73.690424
4           5  58.658816
..        ...        ...
95         96  86.459280
96         97  76.114836
97         98  78.459360
98         99  89.443696
99        100  47.476761

[100 rows x 2 columns]

In [9]:
df.iloc[0:3]

,Player_ID,Age,Height_cm,Weight_kg,Position,Injury_Type,Injury_Severity,Rehabilitation_Program,Rehabilitation_Time_weeks,Injury_Recurrence,Date_of_Injury,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
0,1,24,195,108,Center,ACL Tear,Severe,Physiotherapy,7,0,2017-12-19,0.862860,78.327638,77.705191,37.926663,56.578469,64.259747
1,2,32,183,87,Forward,Ankle Sprain,Mild,Physiotherapy,8,0,2017-08-10,0.806708,32.751850,83.215950,98.938884,71.320646,45.484661
2,3,28,208,109,Center,Knee Injury,Moderate,Flexibility Exercises,3,0,2018-11-21,0.709122,85.958728,71.694712,88.722866,48.764455,99.136761

In [11]:
df.loc[:, ["Age", "Rehabilitation_Time_weeks"]]

    Age  Rehabilitation_Time_weeks
0    24                          7
1    32                          8
2    28                          3
3    25                         11
4    24                          3
..  ...                        ...
95   32                          6
96   31                         11
97   20                         11
98   18                          6
99   22                          8

[100 rows x 2 columns]

In [13]:
df.loc[df.Injury_Recurrence >= 1]

,Player_ID,Age,Height_cm,Weight_kg,Position,Injury_Type,Injury_Severity,Rehabilitation_Program,Rehabilitation_Time_weeks,Injury_Recurrence,Date_of_Injury,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
4,5,24,178,80,Guard,Shoulder Dislocation,Moderate,Balance Training,3,1,2015-03-05,0.933032,35.723132,58.828864,94.458932,58.658816,32.759877
5,6,28,184,97,Guard,Ankle Sprain,Severe,Physiotherapy,11,1,2018-05-29,0.522609,91.150504,54.420779,90.892745,68.643303,79.390262
8,9,25,182,100,Center,Ankle Sprain,Moderate,Balance Training,2,1,2017-06-07,0.905277,49.381435,97.551884,57.930189,96.391731,69.756166
13,14,19,199,95,Forward,ACL Tear,Moderate,Strength Training,8,1,2021-10-23,0.984957,55.933047,34.654739,53.344942,92.618656,94.707734
14,15,18,206,71,Guard,Ankle Sprain,Severe,Strength Training,11,1,2017-02-08,0.921059,63.916609,81.878445,57.871809,85.989868,97.974077
15,16,29,192,70,Center,Knee Injury,Moderate,Strength Training,4,1,2019-11-14,0.919164,73.277834,70.213118,67.617692,59.764945,96.098654
17,18,34,184,74,Guard,ACL Tear,Moderate,Flexibility Exercises,10,1,2015-10-05,0.707410,62.377430,39.784066,54.244220,48.807415,90.342986
21,22,32,201,104,Guard,Shoulder Dislocation,Moderate,Flexibility Exercises,10,1,2015-08-05,0.906451,79.934471,41.498606,45.722338,39.754925,32.590534
22,23,29,176,88,Guard,Knee Injury,Mild,Flexibility Exercises,5,1,2015-11-14,0.999859,92.664479,87.020230,61.670766,88.445117,71.738891
24,25,22,197,72,Center,Shoulder Dislocation,Mild,Strength Training,2,1,2016-10-07,0.777716,67.247944,66.614580,42.347089,66.798313,38.439682
41,42,25,175,87,Forward,Knee Injury,Moderate,Flexibility Exercises,11,1,2016-05-12,0.760082,36.084420,38.182863,34.695353,72.036180,91.229117
44,45,23,178,85,Guard,Hamstring Strain,Severe,Strength Training,6,1,2019-07-28,0.780469,82.180763,53.443393,92.863800,94.008836,85.914827
53,54,32,208,76,Forward,Shoulder Dislocation,Moderate,Balance Training,4,1,2014-05-12,0.568186,72.404237,47.394240,66.707319,47.174438,83.779139
66,67,26,188,103,Guard,Shoulder Dislocation,Severe,Flexibility Exercises,6,1,2015-02-04,0.974760,98.766503,40.494220,40.930682,48.358483,59.944119
67,68,18,171,90,Center,Ankle Sprain,Severe,Balance Training,11,1,2016-08-22,0.573537,37.842723,46.047598,80.118056,71.655455,56.902865
69,70,25,201,102,Forward,Shoulder Dislocation,Severe,Physiotherapy,8,1,2021-06-05,0.746058,97.862930,80.402558,31.896719,64.745637,45.277772
78,79,24,203,99,Forward,Ankle Sprain,Moderate,Strength Training,10,1,2021-04-06,0.564440,49.598537,58.059599,46.672795,60.437914,41.692376
81,82,26,180,104,Forward,Hamstring Strain,Severe,Strength Training,2,1,2015-04-14,0.569414,52.657547,40.734598,80.558685,85.959112,95.991224
82,83,25,185,106,Guard,Knee Injury,Mild,Flexibility Exercises,8,1,2021-06-01,0.820437,59.780551,71.036088,89.898753,78.628753,75.475265
83,84,29,202,93,Forward,Shoulder Dislocation,Mild,Balance Training,6,1,2016-03-08,0.590940,65.532727,65.412208,88.115391,49.050160,72.541576
88,89,20,172,90,Center,Knee Injury,Severe,Strength Training,4,1,2017-02-27,0.586160,70.686675,69.559323,92.743507,39.577304,43.050678
90,91,25,205,92,Guard,Shoulder Dislocation,Mild,Physiotherapy,7,1,2019-05-20,0.520434,63.679807,94.574957,35.985597,61.220404,54.508768
91,92,20,188,102,Center,Hamstring Strain,Mild,Physiotherapy,10,1,2020-09-03,0.584468,67.281260,79.506704,44.552038,42.959305,34.048987
92,93,18,195,72,Forward,ACL Tear,Severe,Balance Training,6,1,2021-06-01,0.639295,33.627648,40.677733,31.857254,67.933066,97.837184
96,97,31,201,72,Forward,Ankle Sprain,Moderate,Flexibility Exercises,11,1,2018-02-19,0.730389,99.297216,81.551096,92.487020,76.114836,42.172667

In [31]:
df.isnull()

,Player_ID,Age,Height_cm,Weight_kg,Position,Injury_Type,Injury_Severity,Rehabilitation_Program,Rehabilitation_Time_weeks,Injury_Recurrence,Date_of_Injury,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
df.isna()

,Player_ID,Age,Height_cm,Weight_kg,Position,Injury_Type,Injury_Severity,Rehabilitation_Program,Rehabilitation_Time_weeks,Injury_Recurrence,Date_of_Injury,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
df.isna().sum()

Player_ID                          0
Age                                0
Height_cm                          0
Weight_kg                          0
Position                           0
Injury_Type                        0
Injury_Severity                    0
Rehabilitation_Program             0
Rehabilitation_Time_weeks          0
Injury_Recurrence                  0
Date_of_Injury                     0
Rehabilitation_Efficiency_Score    0
knee_angle_deg                     0
jump_height_cm                     0
ankle_flexion_deg                  0
speed_m_s                          0
reaction_time_ms                   0
dtype: int64

In [20]:
df.isnull().sum().sum()

0

In [22]:
df.isna().any()

Player_ID                          False
Age                                False
Height_cm                          False
Weight_kg                          False
Position                           False
Injury_Type                        False
Injury_Severity                    False
Rehabilitation_Program             False
Rehabilitation_Time_weeks          False
Injury_Recurrence                  False
Date_of_Injury                     False
Rehabilitation_Efficiency_Score    False
knee_angle_deg                     False
jump_height_cm                     False
ankle_flexion_deg                  False
speed_m_s                          False
reaction_time_ms                   False
dtype: bool

In [23]:
df.describe()

,Player_ID,Age,Height_cm,Weight_kg,Rehabilitation_Time_weeks,Injury_Recurrence,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,25.480000,190.060000,92.070000,6.92000,0.250000,0.745052,60.999925,68.229856,60.652999,64.283236,67.521431
std,29.011492,4.835642,12.126288,11.446189,2.95652,0.435194,0.148033,19.287205,19.188804,20.473906,19.424545,22.198475
min,1.000000,18.000000,170.000000,70.000000,2.00000,0.000000,0.507272,31.404984,31.267713,30.324242,30.769708,31.251175
25%,25.750000,21.000000,179.500000,85.000000,4.75000,0.000000,0.605653,44.764634,53.820140,42.726347,48.281897,46.341198
50%,50.500000,25.000000,192.000000,94.000000,7.00000,0.000000,0.735664,58.288835,70.276652,58.332403,65.534938,67.394995
75%,75.250000,29.000000,201.000000,102.000000,9.25000,0.250000,0.879300,74.268322,85.296794,76.527202,80.493213,89.424590
max,100.000000,34.000000,209.000000,109.000000,11.00000,1.000000,0.999859,99.297216,97.551884,99.781198,98.908153,99.855388

In [25]:
df.loc[df.Age.isna()]

Empty DataFrame
Columns: [Player_ID, Age, Height_cm, Weight_kg, Position, Injury_Type, Injury_Severity, Rehabilitation_Program, Rehabilitation_Time_weeks, Injury_Recurrence, Date_of_Injury, Rehabilitation_Efficiency_Score, knee_angle_deg, jump_height_cm, ankle_flexion_deg, speed_m_s, reaction_time_ms]
Index: []

In [26]:
df.duplicated().sum()

0

In [27]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [28]:
df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [29]:
df.dtypes

Player_ID                            int64
Age                                  int64
Height_cm                            int64
Weight_kg                            int64
Position                            object
Injury_Type                         object
Injury_Severity                     object
Rehabilitation_Program              object
Rehabilitation_Time_weeks            int64
Injury_Recurrence                    int64
Date_of_Injury                      object
Rehabilitation_Efficiency_Score    float64
knee_angle_deg                     float64
jump_height_cm                     float64
ankle_flexion_deg                  float64
speed_m_s                          float64
reaction_time_ms                   float64
dtype: object

In [38]:
df.loc[df.knee_angle_deg < 35]

,Player_ID,Age,Height_cm,Weight_kg,Position,Injury_Type,Injury_Severity,Rehabilitation_Program,Rehabilitation_Time_weeks,Injury_Recurrence,Date_of_Injury,Rehabilitation_Efficiency_Score,knee_angle_deg,jump_height_cm,ankle_flexion_deg,speed_m_s,reaction_time_ms
1,2,32,183,87,Forward,Ankle Sprain,Mild,Physiotherapy,8,0,2017-08-10,0.806708,32.751850,83.215950,98.938884,71.320646,45.484661
7,8,21,195,92,Forward,Ankle Sprain,Mild,Physiotherapy,9,0,2014-05-26,0.688232,34.275457,88.143359,71.389281,50.612603,42.640274
19,20,33,205,101,Forward,Ankle Sprain,Moderate,Balance Training,11,0,2013-11-29,0.528188,32.567824,44.113912,81.625087,74.343475,52.337033
31,32,19,180,105,Guard,Ankle Sprain,Severe,Strength Training,7,0,2019-03-03,0.977026,31.404984,62.387585,30.916612,49.183865,67.764390
92,93,18,195,72,Forward,ACL Tear,Severe,Balance Training,6,1,2021-06-01,0.639295,33.627648,40.677733,31.857254,67.933066,97.837184
95,96,32,189,100,Center,Knee Injury,Mild,Physiotherapy,6,0,2021-11-25,0.560318,34.436248,59.689147,59.499719,86.459280,99.643548